#!/usr/bin/env bash
# (bash v4 required)
#
# metacheck & hashcheck - David Kotz 2019,20,21,22
# AVAILABILITY: https://github.com/dfkotz/metahashcheck
# LICENSE: see LICENSE.md
# USAGE: see README.md, and function usage() below. 
#
# Record metadata for all files in the given directory trees,
# and compare with the metadata recorded earlier.
#  - When run as 'hashcheck' it records hash & size in '.hashcheck' files;
#  - When run as 'metacheck' it records time & size in '.metacheck' files.
#
# Below "checkfiles" and "$cf" refers to .hashcheck or .metacheck files.
#  .metacheck.* and .hashcheck.* are temporary files used during operation.
#  .metacheck-* and .hashcheck-* are retained after verify for use by --accept.
#
# When run with --create, we create .metacheck or .hashcheck 
#   to match the current reality.
# When run with --expand, we update .metacheck or .hashcheck 
#   by adding any newly added files; no changes made for existing files.
# When run with --verify, we create .metacheck-new or .hashcheck-new 
#   according to current reality, and compare them with existing checkfiles;
#   any new, changed, or missing files are noted.
# When run with --accept, we move .metacheck-new or .hashcheck-new to
#   replace the current checkfiles.
# When run with --review, we quickly look to see whether any directory has
#   some files that are newer than its current checkfiles.
# When run with --update, we act add new files (like --expand) but we also
#   alert to missing files (like --verify), but we do not check contents
#   of existing files.
#
# For use in Lightroom, one might also try the following plugin:
#    http://bayimages.net/blog/lightroom/validator/
#
# LIMITATIONS:
#   When the underlying directories are managed by Dropbox, the file size
# will (as of 2022) be zero when Dropbox drops it from local storage; this
# can confuse metacheck. The code highlights files as "MIGRATED".  It also
# highlights files that Dropbox restores (thus size changing from zero to
# non-zero. The limitation is that we do not keep a record of the original
# file size, and thus metacheck will not detect the situation where Dropbox
# silently changes the file size. However, hashcheck will catch that case...
# though running hashcheck over a large Dropbox folder will force all the files
# to be retrieved from Dropbox.

export LC_ALL=C # ensure consistent sort order with native-byte values

problems=""     # updated if errors, deletions, or changes discovered.
additions=""    # updated if additions discovered.
need2review=""  # updated during --review with directories needing verify.
need2accept=""  # updated in cfcompare, with list of dirs that changed.

# Functionality depends on the name of this script:
case "${0##*/}" in
hashcheck)
    progname=hashcheck
    cf=.hashcheck   # shorthand for the basename of in-directory checkfiles.
    tmp=/tmp/hashcheck$$  # another scratch file outside of working directories
    ;;
metacheck)
    progname=metacheck
    cf=.metacheck   # shorthand for the basename of in-directory checkfiles.
    tmp=/tmp/metacheck$$  # another scratch file outside of working directories
    ;;
*)
    echo "$0: must be run as script named 'hashcheck' or 'metacheck'."
    exit 1;;
esac

function usage() {
cat <<EOF
 usage:
   $progname --mode dir...
 where 'mode' is one of
   create: create new records from scratch; error if prior records exist.
   expand: add new records for any newly-added files.
   verify: verify files against prior records, and report differences.
   accept: replace prior records with results from a 'verify' pass.
   review: quickly review dir for presence of files newer than records.
   update: add new records (like expand) and alert to missing files.
EOF
}

# in what mode shall we operate?
case "$1" in
    "--create") mode=create;;  # for the first time on a new directory
    "--expand") mode=expand;;  # to add entries for newly added files
    "--verify") mode=verify;;  # to scan a directory and report changes
    "--accept") mode=accept;;  # to accept results of --verify
    "--review") mode=review;;  # to review whether --verify is needed
    "--update") mode=update;;  # like expand, but alert to missing files
    *)  usage; exit 1;;
esac
shift

# on what platform do we operate? (see cfxargs below)
platform=$(uname)
case $platform in
    Darwin)  linux=no;;
    FreeBSD) linux=no;;
    Linux)   linux=yes;;
    *)
        echo Platform $platform not supported by this command.
        exit 2;
esac

# how many directories will we scan?
if [[ $# -lt 1 ]]; then 
    usage; exit 3;
fi

# all modes (except create) expect to find $cf in each directory argument
nerr=0
if [ $mode == "create" ]; then
    # each argument must be a directory
    for arg in "$@"
    do
        if [ ! -d "$arg" ]; then
            echo "ERROR: not a directory: $arg"
            let nerr++
        fi
    done
else
    # ensure each directory argument has something to scan
    for arg in "$@"
    do
        # only consider directories; ignore all others
        if [ -d "$arg" ]; then
            nfound=$(find "$@" -name $cf | wc -l)
            if [ $nfound -eq 0 ]; then
                echo "ERROR: no $cf found in directory $arg"
                let nerr++
            fi
        else
            echo "WARNING: not a directory: $arg"
        fi
    done
fi

if [ $nerr -gt 0 ]; then
   exit 4
fi

###################################################################
# A function for cleaning up our work if interrupted
# TODO: it cleans up only the current directory. need do others?
function cleanall {
    echo cleaning up all files...
    rm -f $cf.* $cf-*
}
function cleantmp {
    echo cleaning up temp files...
    rm -f $cf.* $tmp $tmp.*
}
function cleanall-and-exit {
    cleanall
    exit 99
}

# this trap will only clean the current directory - not all 
trap cleanall-and-exit sigint

# next: several functions.  skip down to "main loop" below...


###################################################################
# Determine whether this file is under Dropbox control and its size
# has changed from non-zero to zero (as Dropbox removes it from local
# storage) or from zero to non-zero (as Dropbox restores it).
# Return 0 if so, non-zero otherwise.
# Parameters: pathname oldSize newSize
function dropboxSizeEffect {
    if [[ $(uname) != Darwin ]]; then
        # not on MacOS, thus no Dropbox
        return 1
    fi

    # extract command parameters
    temp="${1%\'}"    # in case pathname is 'quoted', remove any trailing quote
    name="${temp#\'}" # and remove any leading quote
    oldSize="$2"
    newSize="$3"

    if (( $oldSize != 0 && $newSize != 0 )); then
        # both sizes non-zero: this is not a Dropbox effect
        return 1
    fi

    if ls -l@ "$name" | grep -q com.dropbox ; then
        # Dropbox attributes present: this file is under Dropbox management
        return 0
    else
        # Dropbox attributes not present: no excuse for change in file size
        return 1
    fi
}

###################################################################
# A function to push null-terminated filenames, from stdin,
# through 'xargs' with a commandline appropriate to our mode of operation
# and to the platform on which we run.  This function is where
# metacheck and hashcheck actually differ!
# No arguments expected; stdin should be result of `find... -print0`.
# outputs three columns: 
# 1 checksum(hash) or last-modification-time
# 2 size in bytes
# 3 filename
function cfxargs {
    # Sadly, the 'xargs' and 'stat' commands differ between MacOS/BSD and Linux.
    # xargs: on MacOS/BSD, empty input does not run the command; on Linux, need -r.
    # stat: format with -f on MacOS/BSD and -c on Linux, with different %specifiers.
    if [ $linux == no ]
    then # MacOS or FreeBSD
        if [ $progname == hashcheck ]
        then # hashcheck
            xargs -0 cksum
        else # metacheck
            xargs -0 stat -f "%m %z %N"
        fi
    else # Linux
        if [ $progname == hashcheck ]
        then # hashcheck
            xargs -0 -r cksum
        else # metacheck
            xargs -0 -r stat -c "%Y %s %n"
        fi
    fi
}


###################################################################
# A function to list all the relevant new files in current directory;
# arguments to cflist are passed to end of 'find' command; caller should
# add argument -print or -print0 depending on desired output format.
function cflist {
    find . \( -type f -and -not -name .\* -and -not -name Icon\? \) "$@"
    return $?
}

###################################################################
# A function to create a new checkfile from existing files;
# creates $cf-new and returns 0 on success, non-zero on error.
function cfcreate {
    if cflist -print0 | cfxargs | sort --key=3 > $cf-new
    then
        return 0
    else 
        rm -f $cf-new
        return 1
    fi
}

###################################################################
# A function to extend a checkfile with additional files whose names
# are listed, one per line, in the standard input;
# creates $cf-new and returns 0 on success, non-zero on error.
function cfextend {
    if tr \\n \\000 | cfxargs | cat $cf - | sort --key=3 > $cf-new
    then
        return 0
    else 
        rm -f $cf-new
        return 1
    fi
}

###################################################################
# A function to compare a new checkfile with existing checkfile;
# expects to find $cf and $cf-new, each with three columns:
# 1 checksum(hash) or last-modification-time
# 2 size in bytes
# 3 filename
# and returns 0 on success, non-zero if any changes detected
function cfcompare {
    # quickly compare new records with existing records
    if cmp --quiet $cf $cf-new ; then
        echo NO ADDITIONS, DELETIONS, OR CHANGES.
        return 0
    fi

    # something changed, so we need to look more closely.
    echo SOMETHING CHANGED! 
    # we will later recommend accepting the new $cf for this directory.
    need2accept="$need2accept '$dir'"

    declare -i added=0 lost=0 changed=0 migrated=0
    
    # load the existing checkfile into Old
    declare -A OldCol1 OldCol2
    while read col1 col2 name;
    do OldCol1["${name@Q}"]=$col1; OldCol2["${name@Q}"]=$col2;
    done < $cf
    
    # load the new checkfile into New
    declare -A NewCol1 NewCol2
    while read col1 col2 name;
    do NewCol1["${name@Q}"]=$col1; NewCol2["${name@Q}"]=$col2;
    done < $cf-new
    
    echo ${#OldCol1[@]} files in Old
    echo ${#NewCol1[@]} files in New
    
    # loop over all the old files to see what disappeared or changed
    for name in "${!OldCol1[@]}"
    do
        # echo considering "${name}"
        oldvalu=${OldCol1["${name}"]} # hash if hashcheck, time if metacheck
        newvalu=${NewCol1["${name}"]} # hash if hashcheck, time if metacheck
        oldSize=${OldCol2["${name}"]} # file size
        newSize=${NewCol2["${name}"]} # file size

        if [[ ! -v NewCol1["${name@Q}"] ]] ; then
            echo "LOST $name"
            let lost++
        elif [[ $oldvalu -ne $newvalu ]] ; then
            echo "CHANGED $name"
            let changed++
        elif [[ $oldSize -ne $newSize ]] ; then
            # This situation is tricky; Dropbox can change the file size
            # to zero when it flushes a file from local storage,
            # or change it to non-zero when it restores the file.
            if dropboxSizeEffect "${name}" $oldSize $newSize
            then
                echo "MIGRATED $name"
                let migrated++
            else
                echo "CHANGED $name"
                let changed++
            fi
        fi
    done
    
    # loop over all the new files to see what was added
    # additions are not necessarily a problem, so don't print the names
    for name in "${!NewCol1[@]}"
    do
        if [[ ! -v OldCol1["${name@Q}"] ]] ; then
            # echo "ADDED $name"
            let added++
        fi
    done

    if [[ $added -gt 0 ]]; then
        echo "ADDED $added files"
        additions+=" '$dir': $added files added;"
    fi
    if [[ $changed -gt 0 ]]; then
        problems+=" '$dir': $changed files changed;"
    fi
    if [[ $lost -gt 0 ]]; then
        problems+=" '$dir': $lost files lost;"
    fi
    if [[ $migrated -gt 0 ]]; then
        problems+=" '$dir': $migrated files migrated;"
    fi
    
    # return number of files added, changed, lost, or migrated (ideally zero)
    return $(( $added + $changed + $lost + $migrated ))
}

###################################################################
# Execute mode 'create' in current working directory.
# Required for the first pass over a new directory, to compute records 
# of all files in the directory tree, and create $cf file.
function mode-create {
    if [[ -f $cf ]]; then
        # don't overrwrite an existing checkfile
        echo "error: $cf already exists for '$dir'"
        echo "skipping '$dir'..."
        problems+=" '$dir': $hc already exists;"
        return 1
    fi
    
    if cfcreate; then
        # save the new file
        mv -f $cf-new $cf
        echo "created $cf for directory '$dir'"
        return 0
    else
        problems+=" '$dir': cfcreate failed;"
        return 1
    fi
}

###################################################################
# Execute either mode 'expand' or 'update' in current working directory.
# This extends the current $cf file with new records for any new files;
# it also produces a list of misisng files, like in mode-verify.
# It does not verify or re-compute records for existing files.
# Assumes caller has verified ./$cf exists.
function mode-expandupdate {
    # first, make a list of filenames in the directory
    if ! ( cflist -print | sort > $tmp.new ); then
        echo "trouble listing files... giving up on '$dir'"
        problems+=" '$dir': trouble;"
        return 1
    fi

    # next, make a list of filenames in $cf, by stripping off first two numbers
    sed 's/^[0-9]* [0-9]* //' $cf | sort > $tmp.old

    # now compare the two lists, to find filenames that are not in $cf
    comm -13 $tmp.old $tmp.new > $tmp.add
    # count the number of additional files
    added=$(cat $tmp.add | wc -l)
    if [ $added -gt 0 ]; then
        # some files to be added
        if cfextend < $tmp.add; then
            echo ADDED $added files.
            # save the new file
            mv -f $cf-new $cf
            additions+=" '$dir': $added files added;"
            result=0
        else
            echo FAILED in adding $added files...
            problems+=" '$dir': cfextend failed;"
            result=1
        fi
    else
        # no files exist that are not already listed in $cf
        echo "no new files to be added."
        result=0
    fi

    # unless we're in update mode, we're done
    if [ $mode != "update" ]; then
        return $result
    fi

    # now compare the two lists, to find filenames that disappeared
    comm -23 $tmp.old $tmp.new > $tmp.lost
    # count the number of lost files
    lost=$(cat $tmp.lost | wc -l)
    if [ $lost -gt 0 ]; then
        # we lost some files, and need to remove them from $cf;
        # build an awk script to help us do that.
        echo  > $tmp.awk 'BEGIN { while (getline < LOST) { lost[$0] = 1 } }'
        echo >> $tmp.awk '{'
        echo >> $tmp.awk ' filename=$0; sub(/[0-9]* [0-9]* /, "", filename);'
        echo >> $tmp.awk ' if (filename in lost)'
        echo >> $tmp.awk '      { print "LOST", filename }'
        echo >> $tmp.awk ' else { print  > "/dev/stderr" }'
        echo >> $tmp.awk '}'
        # notice how the awk script passes non-lost files to stderr,
        # but prints warning messages to stdout (as do we in this script).

        # create $cf-new so the user can later --accept these changes:
        awk -f $tmp.awk -v LOST=$tmp.lost < $cf 2> $cf-new

        # we will later recommend accepting the new $cf for this directory.
        need2accept="$need2accept '$dir'"
        problems+=" '$dir': $lost files lost;"
        result=1
    fi

    return $result
}

###################################################################
# Execute mode 'expand' in current working directory.
# This extends the current $cf file with new records for any new files.
# It does not verify or re-compute records for existing files.
# Assumes caller has verified ./$cf exists.
function mode-expand {
    echo "expanding '$dir' by looking for new files"
    mode-expandupdate
    return $?
}

###################################################################
# Execute mode 'update' in current working directory.
# This extends the current $cf file with new records for any new files;
# it also produces a list of misisng files, like in mode-verify.
# It does not verify or re-compute records for existing files.
# Assumes caller has verified ./$cf exists.
function mode-update {
    echo "updating '$dir' by looking for new or missing files"
    mode-expandupdate
    return $?
}

###################################################################
# Execute mode 'verify' in current working directory.
# This time-consuming pass computes new records for all the files
# in the directory tree, and compares them against the pre-existing
# records in $cf.  If there are any differences, it leaves behind $cf-new;
# later, if the user decides to accept the changes, the user should
# run again with --accept.
# Assumes caller has verified ./$cf exists.
function mode-verify {
    if cfcreate; then
        if cfcompare; then
            # no changes, no need for later --accept, don't keep $cf-new
            rm -f $cf-new
            return 0
        else
            # some changes were noted, or failures occurred
            problems+=" '$dir': cfcompare failed or found differences;"
            return 1
        fi
    else
        problems+=" '$dir': cfcreate failed;"
        return 2
    fi
}

###################################################################
# Execute mode 'accept' in current working directory.
# Assuming a --verify pass has been run recently on this directory,
# leaving a $cf-new file behind, this --accept pass simply
# overwrites $cf with $cf-new.
# Assumes caller has verified ./$cf exists.
function mode-accept {
    # can't accept if there is not a new checkfile
    if [[ ! -f $cf-new ]]; then
        echo "error: $cf-new missing for '$dir'"
        echo "perhaps because you did not run 'verify' first."
        echo "to create, $0 --verify '$dir'"
        echo "skipping '$dir'..."
        problems+=" '$dir': missing $cf-new;"
        return 1
    fi
    
    echo updating $cf...
    mv -f $cf-new $cf
    return 0
}


###################################################################
# Execute mode 'review' in current working directory.
# This scans the directory to see if there are any subdirectories
# or files that are newer than the $cf file.  If so, that's 
# a clear sign that the directory needs --verify.  The main script 
# outputs a suggested commandline.
# Assumes caller has verified ./$cf exists.
function mode-review {
    echo "reviewing '$dir' for files newer than $cf..."
    if ! newer=$(cflist -newer $cf -print | wc -l); then
        echo "trouble listing files... giving up on '$dir'"
        problems+=" '$dir': trouble;"
        return 1
    fi
    if [ $newer -gt 0 ]; then
        # some files or directories newer than $cf
        need2review="$need2review '$dir'"
        return 1
    else
        # no files or directories newer than $cf
        return 0
    fi
}


###################################################################
######################### main loop ###############################

# first, make an array of directories to be processed.
if [ $mode == create ]; then
    # process each command-line dir literally.
    dirs=("$@")
    ndirs=${#dirs[@]}
    echo "create $cf in each of $ndirs directories..."
else
    # make an array of subdirs containing file $cf, 
    # anywhere under each directory in the command-line arguments..
    echo search for $cf in $# arguments...

    # Here it gets tricky; we use 'find' to look for all $cf in any subdir
    # of any argument "$@", and 'sed' to trim each pathname to subdir name;
    # we need to temporarily modify IFS so each line of output becomes one
    # element of the array 'dirs'; supports pathnames with embedded spaces.
    # The 'sort' makes it easier to see progress in long runs.
    oldIFS="$IFS"; IFS=$'\n'
    dirs=($(find "$@" -name $cf | sed s+/$cf++ | sort))
    IFS="$oldIFS"

    # did we find anything?
    ndirs=${#dirs[@]}
    if [ $ndirs -eq 0 ]; then
        problems+=" no $cf found under any argument listed;"
    else
        echo "$mode $cf in each of $ndirs directories..."
    fi
fi
    
# loop over all dirs, processing each directory independently
for dir in "${dirs[@]}"
do
    echo $ndirs directories remaining to examine
    if cd "$dir"; then
        echo "examine directory '$dir'"...
    else
        echo "cannot cd '$dir'; ...skipping"
        problems+=" '$dir': error with 'cd';"
        continue
    fi
    
    case $mode in
        create) mode-create;;
        expand) mode-expand;;
        verify) mode-verify;;
        accept) mode-accept;;
        review) mode-review;;
        update) mode-update;;
        *) ;;
    esac
    
    echo -n "done... popping back to "
    cd -   # pop back to where we were before cd $dir

    let ndirs--
    echo
done

# Check the results of the above loop.
if [ $mode == review ]; then
    if [ "$need2review" == "" ]; then
        echo "No directories appear to need verification."
    else
        echo "NEED VERIFICATION; run the following":
        echo "$progname --verify $need2review"
    fi
fi

if [ "$problems" ]; then
    echo "Warning: errors or changes found in these directories:"
    echo "$problems" | tr \; \\n
    echo "$additions" | tr \; \\n
    if [ "$need2accept" ]; then
        echo "IFF those changes were acceptable, run the following:"
        echo "$progname --accept $need2accept"
    fi
    exit 5
else
    echo "NO PROBLEMS FOUND."
    if [ "$need2accept" ]; then
        echo "BUT, some files were added in some directories."
        echo "$additions" | tr \; \\n
        echo "Thus, the following command is recommended:"
        echo $progname --accept $need2accept

        echo
        echo "The following command is also recommended:"
        if [ $progname == hashcheck ]; then
            echo metacheck --verify $need2accept
        else
            echo hashcheck --verify $need2accept
        fi
        # technically not a failure, but exit non-zero to get your attention
        exit 6
    else
        # no problems, and no new files needing acceptance
        exit 0
    fi
    # unreached; the preceding if statement should always exit
    echo ERROR: reached unreachable point 1; exit 98
fi
# unreached; the preceding if statement should always exit
echo ERROR: reached unreachable point 2; exit 99
